/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package smartkitchen.view;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.*;
import com.toedter.calendar.JDateChooser;


/**
 *
 * @author ASUS
 */
public class ZeroWaste extends javax.swing.JFrame {
    private Connection conn;
    

    /**
     * Creates new form MainMenu
     */
    public ZeroWaste() {
        initComponents();
        connectDatabase();
        loadData();
    }
    
    private void connectDatabase() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/smartkitchen?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC";
            String user = "root";
            String pass = "";
            conn = DriverManager.getConnection(url, user, pass);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal koneksi database:\n" + e.getMessage());
            System.exit(0);
        }
    }

    private void loadData() {
        try {
            String sql = "SELECT * FROM stok_bahan";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            DefaultTableModel model = (DefaultTableModel) tabelStok.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                int id = rs.getInt("id");
                String nama = rs.getString("nama_bahan");
                int jumlah = rs.getInt("jumlah");
                Date kadaluarsa = rs.getDate("kadaluarsa");
                String tanggal = (kadaluarsa != null) ? kadaluarsa.toString() : "";

                model.addRow(new Object[]{id, nama, jumlah, tanggal});
            }
            rs.close();
            st.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal load data:\n" + e.getMessage());
        }
    }
    
    private void tambahData(String nama, int jumlah, String kadaluarsa) {
        try {
            String sql = "INSERT INTO stok_bahan (nama_bahan, jumlah, kadaluarsa) VALUES (?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, nama);
            pst.setInt(2, jumlah);

            Date tanggal = null;
            try {
                tanggal = Date.valueOf(kadaluarsa);
            } catch (IllegalArgumentException ex) {
                tanggal = null;
            }
            pst.setDate(3, tanggal);

            pst.executeUpdate();
            pst.close();

            loadData();
            JOptionPane.showMessageDialog(this, "Data berhasil ditambah");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal tambah data:\n" + e.getMessage());
        }
    }

    private void hapusData(String idStr) {
        try {
            int id = Integer.parseInt(idStr);
            String sql = "DELETE FROM stok_bahan WHERE id = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, id);

            int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin hapus data ID " + id + "?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                int rows = pst.executeUpdate();
                if (rows > 0) {
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
                    loadData();
                } else {
                    JOptionPane.showMessageDialog(this, "Data tidak ditemukan");
                }
            }
            pst.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal hapus data:\n" + e.getMessage());
        }
    }
    private void resetAutoIncrement() {
    try {
        String sql = "ALTER TABLE stok_bahan AUTO_INCREMENT = 1";
        Statement st = conn.createStatement();
        st.executeUpdate(sql);
        st.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal reset auto increment:\n" + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        NamaBahan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        spinnerJumlah = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelStok = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnDelete1 = new javax.swing.JButton();
        btnDelete2 = new javax.swing.JButton();
        btnSave1 = new javax.swing.JButton();
        dateChooserKadaluarsa = new com.toedter.calendar.JDateChooser();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(196, 225, 230));

        jLabel1.setText("Nama Bahan");

        NamaBahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaBahanActionPerformed(evt);
            }
        });

        jLabel2.setText("Jumlah");

        spinnerJumlah.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setText("Kadaluarsa");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        tabelStok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama Bahan", "Jumlah", "Tanggal Kadaluarsa", "Jenis Bahan"
            }
        ));
        jScrollPane1.setViewportView(tabelStok);

        jLabel4.setText("ZeroWasteSmartKitchen");

        btnDelete1.setText("Clear");
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear(evt);
            }
        });

        btnDelete2.setText("Edit");
        btnDelete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit(evt);
            }
        });

        btnSave1.setText("Cetak");
        btnSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetak(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spinnerJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                    .addComponent(btnDelete2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NamaBahan)
                                    .addComponent(dateChooserKadaluarsa, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDelete1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSave1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(221, 221, 221)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(NamaBahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(spinnerJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(dateChooserKadaluarsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        btnDelete1.getAccessibleContext().setAccessibleName("Clear");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NamaBahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaBahanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaBahanActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
      
    String nama = NamaBahan.getText();
        int jumlah = (int) spinnerJumlah.getValue();
        java.util.Date utilDate = dateChooserKadaluarsa.getDate();

        if (nama.isEmpty() || utilDate == null) {
            JOptionPane.showMessageDialog(this, "Nama bahan dan tanggal kadaluarsa harus diisi");
            return;
        }

        String tanggal = new java.sql.Date(utilDate.getTime()).toString();
        tambahData(nama, jumlah, tanggal);

        NamaBahan.setText("");
        spinnerJumlah.setValue(0);
        dateChooserKadaluarsa.setDate(null);


    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
         int row = tabelStok.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus dari tabel");
            return;
        }
        String id = tabelStok.getValueAt(row, 0).toString();
        hapusData(id);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClear(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear
        NamaBahan.setText("");
        spinnerJumlah.setValue(0);
        dateChooserKadaluarsa.setDate(null);
    }//GEN-LAST:event_btnClear
private Integer idYangSedangDiedit = null;
    private void btnEdit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit
            int row = tabelStok.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Pilih baris dari tabel yang ingin diedit");
        return;
    }

    String idStr = tabelStok.getValueAt(row, 0).toString();
    String nama = tabelStok.getValueAt(row, 1).toString();
    String jumlahStr = tabelStok.getValueAt(row, 2).toString();
    String tanggalStr = tabelStok.getValueAt(row, 3).toString();

    idYangSedangDiedit = Integer.parseInt(idStr);
    NamaBahan.setText(nama);
    spinnerJumlah.setValue(Integer.parseInt(jumlahStr));

    // Konversi String ke java.util.Date
    try {
        java.util.Date tanggal = java.sql.Date.valueOf(tanggalStr);
        dateChooserKadaluarsa.setDate(tanggal);
    } catch (IllegalArgumentException e) {
        dateChooserKadaluarsa.setDate(null);
    }

    }//GEN-LAST:event_btnEdit

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
            String nama = NamaBahan.getText();
    int jumlah = (int) spinnerJumlah.getValue();
    java.util.Date utilDate = dateChooserKadaluarsa.getDate();

    if (nama.isEmpty() || utilDate == null) {
        JOptionPane.showMessageDialog(this, "Nama bahan dan tanggal kadaluarsa harus diisi");
        return;
    }

    String tanggal = new java.sql.Date(utilDate.getTime()).toString();

    if (idYangSedangDiedit != null) {
        // Mode update
        try {
            String sql = "UPDATE stok_bahan SET nama_bahan = ?, jumlah = ?, kadaluarsa = ? WHERE id = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, nama);
            pst.setInt(2, jumlah);
            pst.setDate(3, java.sql.Date.valueOf(tanggal));
            pst.setInt(4, idYangSedangDiedit);
            pst.executeUpdate();
            pst.close();

            JOptionPane.showMessageDialog(this, "Data berhasil diupdate");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal update data:\n" + e.getMessage());
        }

        idYangSedangDiedit = null;
    } else {
        // Mode tambah
        tambahData(nama, jumlah, tanggal);
    }

    loadData();
    NamaBahan.setText("");
    spinnerJumlah.setValue(0);
    dateChooserKadaluarsa.setDate(null);

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCetak(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetak
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCetak

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {}

        java.awt.EventQueue.invokeLater(() -> {
            new ZeroWaste().setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NamaBahan;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnDelete2;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSave1;
    private javax.swing.JButton btnTambah;
    private com.toedter.calendar.JDateChooser dateChooserKadaluarsa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spinnerJumlah;
    private javax.swing.JTable tabelStok;
    // End of variables declaration//GEN-END:variables
}
